version: "1.0"
services:
  mongodb:
    image: mongo:4.4.9
    volumes:
      - ~/volumes/jhipster/discordProjectManagementBot/mongodb/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=discordbot
      - MONGO_INITDB_ROOT_PASSWORD=verycomplexpassword
      - MONGO_INITDB_DATABASE=projectManagementBot
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
  bot:
    image: lamine2000/project-management-discord-bot:latest
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://discordbot:verycomplexpassword@mongodb:27017/?retryWrites=true&w=majority
      - SPRING_DATA_MONGODB_DATABASE=projectManagementBot
      - SPRING_PROFILES_ACTIVE=docker
    ports:
        - 127.0.0.1:2000:2000
